package thornworks;

import java.io.IOException;
import java.io.PrintWriter;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.*;

/**
 * A text file is read and the output of this file is pumped directly to the client.
 * The purpose of this Servlet is to render log files, so the actual file name of the log file
 * is read from the request URI.
 * @author LaSpina
 */
public class RenderFileServlet extends HttpServlet {

    /**
     * Processes requests for both HTTP
     * <code>GET</code> and
     * <code>POST</code> methods.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
        response.setContentType("text/plain");
        PrintWriter out = response.getWriter();
        try {
            String uri = request.getRequestURI();
            int slashDot = uri.lastIndexOf("/"); 
            String log = uri.substring(slashDot+1);
            File logFile = new File(LogViewServlet.logFolder, log);
            out.println(log);
            out.println();
            log("Sending log file to " + request.getRemoteHost());
            render(logFile, out);
        } 
        catch(IOException ioe) {
            this.log("404 error generated by bad log file request.", ioe);
            response.sendError(404, "Log file not found.");
        }
        finally {            
            out.close();
        }
    }
    
    /**
     * Reads the given file and sends it to the output stream
     * @param sendFile A reference to the file we wish to send to the client.
     * @param out The request output stream.
     */
    private void render(File sendFile, PrintWriter out) throws IOException {
        BufferedReader in = new BufferedReader(new FileReader(sendFile));
        String line;
        while((line = in.readLine()) != null) {
            out.println(line);
        }
    }
}
